# TODO: update the baseurl later...
baseurl: http://alexjlockwood.github.io

name: Android Design Patterns
author:
  name: Alex Lockwood
  email: alex@androiddesignpatterns.com
  profiles:
    - label: Google+
      url: https://plus.google.com/+AlexLockwood

markdown: redcarpet
pygments: true

relative_permalinks: false
permalink: /:year/:month/:title.html
