name: Android Design Patterns
author:
  name: Alex Lockwood
  googleplus: https://google.com/+AlexLockwood
  twitter: https://twitter.com/alexjlockwood
  stackoverflow: http://stackoverflow.com/users/844882
  flickr: http://www.flickr.com/photos/tailorransom
  github: https://github.com/alexjlockwood
  feedburner: http://feeds.feedburner.com/androiddesignpatterns

baseurl: http://www.androiddesignpatterns.com
description: 'Android Design Patterns is a website for developers who wish to better understand the Android application framework. The tutorials here emphasize proper code design and project maintainability.'

paginate: 5

permalink: /:year/:month/:title.html

exclude: ['README.md', 'LICENSE.txt', "_dev", "gulpfile.js", "node_modules", "package.json"]
gems: [jekyll-paginate]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge