name: Android Design Patterns
author:
  name: Alex Lockwood
  googleplus: https://google.com/+AlexLockwood
  twitter: https://twitter.com/alexjlockwood
  stackoverflow: https://stackoverflow.com/users/844882
  flickr: https://www.flickr.com/photos/tailorransom
  github: https://github.com/alexjlockwood
  feedburner: https://feeds.feedburner.com/androiddesignpatterns

baseurl: https://www.androiddesignpatterns.com
description: 'Android Design Patterns is a website for developers who wish to better understand the Android application framework. The tutorials here emphasize proper code design and project maintainability.'

paginate: 5

permalink: /:year/:month/:title.html

exclude: [
  'README.md',
  'LICENSE.txt',
  'gulpfile.js',
  'node_modules',
  'package.json',
  'Gemfile',
  'Gemfile.lock'
]
gems: [jekyll-paginate]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

host: 0.0.0.0
future: true
